const connection = require('../connection2');

const getInformacoesReserva = async (CPF, cod_reserva) => {
  // Verifica se o CPF fez checkin nessa reserva
  const [checkins] = await connection.execute(
    `SELECT c.id
     FROM checkin c
     WHERE c.CPF = ? AND c.cod_reserva = ?`,
    [CPF, cod_reserva]
  );

  if (!checkins.length) {
    return null;
  }

  // Busca reserva, apartamento e prédio em uma única query
  const [rows] = await connection.execute(
    `SELECT
       r.id                        AS reserva_id,
       r.cod_reserva,
       r.start_date,
       r.end_data,
       r.description,
       r.Observacoes,
       r.check_in,
       r.check_out,
       r.early_checkin,
       r.late_checkout,
       r.placa_carro,
       r.marca_carro,
       r.modelo_carro,
       r.cor_carro,
       r.origem,
       a.id                        AS apartamento_id,
       a.nome                      AS apartamento_nome,
       a.endereco                  AS apartamento_endereco,
       a.bairro                    AS apartamento_bairro,
       a.andar                     AS apartamento_andar,
       a.numero_hospedes           AS apartamento_numero_hospedes,
       a.tipo_checkin              AS apartamento_tipo_checkin,
       a.acesso_predio             AS apartamento_acesso_predio,
       a.acesso_porta              AS apartamento_acesso_porta,
       a.senha_porta               AS apartamento_senha_porta,
       a.link_app                  AS apartamento_link_app,
       a.instrucoes_entrada        AS apartamento_instrucoes_entrada,
       a.tem_garagem               AS apartamento_tem_garagem,
       a.vaga_garagem              AS apartamento_vaga_garagem,
       a.ssid_wifi                 AS apartamento_ssid_wifi,
       a.senha_wifi                AS apartamento_senha_wifi,
       a.aceita_pet                AS apartamento_aceita_pet,
       a.ar_condicionado           AS apartamento_ar_condicionado,
       a.qtd_cama_solteiro         AS apartamento_qtd_cama_solteiro,
       a.qtd_cama_casal            AS apartamento_qtd_cama_casal,
       a.qtd_banheiros             AS apartamento_qtd_banheiros,
       a.ferro_passar              AS apartamento_ferro_passar,
       a.secador_cabelo            AS apartamento_secador_cabelo,
       a.cafeteira                 AS apartamento_cafeteira,
       a.ventilador                AS apartamento_ventilador,
       a.sanduicheira              AS apartamento_sanduicheira,
       a.chaleira_eletrica         AS apartamento_chaleira_eletrica,
       a.liquidificador            AS apartamento_liquidificador,
       a.air_fryer                 AS apartamento_air_fryer,
       a.smart_tv                  AS apartamento_smart_tv,
       a.tv_aberta                 AS apartamento_tv_aberta,
       a.tv_quarto                 AS apartamento_tv_quarto,
       a.tipo_chuveiro             AS apartamento_tipo_chuveiro,
       a.tipo_fogao                AS apartamento_tipo_fogao,
       a.escritorio                AS apartamento_escritorio,
       a.aquecedor                 AS apartamento_aquecedor,
       a.aspirador_de_po           AS apartamento_aspirador_de_po,
       a.qtd_sofa_cama             AS apartamento_qtd_sofa_cama,
       a.qtd_taca_vinho            AS apartamento_qtd_taca_vinho,
       a.enxoval_toalhas           AS apartamento_enxoval_toalhas,
       a.enxoval_fronha            AS apartamento_enxoval_fronha,
       a.enxoval_pisos             AS apartamento_enxoval_pisos,
       a.enxoval_rostos            AS apartamento_enxoval_rostos,
       a.enxoval_sobre_lencol_casal    AS apartamento_enxoval_lencol_casal,
       a.enxoval_sobre_lencol_solteiro AS apartamento_enxoval_lencol_solteiro,
       a.respostas_programadas     AS apartamento_respostas_programadas,
       a.tensao_tomadas            AS apartamento_tensao_tomadas,
       a.possui_tomada_220         AS apartamento_possui_tomada_220,
       a.localizacao_lixeira       AS apartamento_localizacao_lixeira,
       a.localizacao_lavanderia    AS apartamento_localizacao_lavanderia,
       a.exame_piscina             AS apartamento_exame_piscina,
       a.pode_hospede_piscina      AS apartamento_pode_hospede_piscina,
       a.piscina_aquecida          AS apartamento_piscina_aquecida,
       a.tamanho_vaga              AS apartamento_tamanho_vaga,
       p.id                        AS predio_id,
       p.nome                      AS predio_nome,
       p.piscina,
       p.academia,
       p.churrasqueira,
       p.salao_de_festas,
       p.espaco_gourmet,
       p.sauna,
       p.spa,
       p.salao_de_jogos,
       p.coworking,
       p.jardim_terraco,
       p.lavanderia,
       p.bicicletario,
       p.estacionamento_visitas,
       p.elevador_social
     FROM reservas r
     LEFT JOIN apartamentos a ON r.apartamento_id = a.id
     LEFT JOIN predios p      ON a.predio_id      = p.id
     WHERE r.cod_reserva = ?`,
    [cod_reserva]
  );

  if (!rows.length) return null;

  const row = rows[0];

  return {
    reserva: {
      id: row.reserva_id,
      cod_reserva: row.cod_reserva,
      start_date: row.start_date,
      end_data: row.end_data,
      description: row.description,
      Observacoes: row.Observacoes,
      check_in: row.check_in,
      check_out: row.check_out,
      early_checkin: row.early_checkin,
      late_checkout: row.late_checkout,
      placa_carro: row.placa_carro,
      marca_carro: row.marca_carro,
      modelo_carro: row.modelo_carro,
      cor_carro: row.cor_carro,
      origem: row.origem,
    },
    apartamento: {
      id: row.apartamento_id,
      nome: row.apartamento_nome,
      endereco: row.apartamento_endereco,
      bairro: row.apartamento_bairro,
      andar: row.apartamento_andar,
      numero_hospedes: row.apartamento_numero_hospedes,
      tipo_checkin: row.apartamento_tipo_checkin,
      acesso_predio: row.apartamento_acesso_predio,
      acesso_porta: row.apartamento_acesso_porta,
      senha_porta: row.apartamento_senha_porta,
      link_app: row.apartamento_link_app,
      instrucoes_entrada: row.apartamento_instrucoes_entrada,
      tem_garagem: row.apartamento_tem_garagem,
      vaga_garagem: row.apartamento_vaga_garagem,
      ssid_wifi: row.apartamento_ssid_wifi,
      senha_wifi: row.apartamento_senha_wifi,
      aceita_pet: row.apartamento_aceita_pet,
      ar_condicionado: row.apartamento_ar_condicionado,
      qtd_cama_solteiro: row.apartamento_qtd_cama_solteiro,
      qtd_cama_casal: row.apartamento_qtd_cama_casal,
      qtd_banheiros: row.apartamento_qtd_banheiros,
      ferro_passar: row.apartamento_ferro_passar,
      secador_cabelo: row.apartamento_secador_cabelo,
      cafeteira: row.apartamento_cafeteira,
      ventilador: row.apartamento_ventilador,
      sanduicheira: row.apartamento_sanduicheira,
      chaleira_eletrica: row.apartamento_chaleira_eletrica,
      liquidificador: row.apartamento_liquidificador,
      air_fryer: row.apartamento_air_fryer,
      smart_tv: row.apartamento_smart_tv,
      tv_aberta: row.apartamento_tv_aberta,
      tv_quarto: row.apartamento_tv_quarto,
      tipo_chuveiro: row.apartamento_tipo_chuveiro,
      tipo_fogao: row.apartamento_tipo_fogao,
      escritorio: row.apartamento_escritorio,
      aquecedor: row.apartamento_aquecedor,
      aspirador_de_po: row.apartamento_aspirador_de_po,
      qtd_sofa_cama: row.apartamento_qtd_sofa_cama,
      qtd_taca_vinho: row.apartamento_qtd_taca_vinho,
      enxoval_toalhas: row.apartamento_enxoval_toalhas,
      enxoval_fronha: row.apartamento_enxoval_fronha,
      enxoval_pisos: row.apartamento_enxoval_pisos,
      enxoval_rostos: row.apartamento_enxoval_rostos,
      enxoval_lencol_casal: row.apartamento_enxoval_lencol_casal,
      enxoval_lencol_solteiro: row.apartamento_enxoval_lencol_solteiro,
      respostas_programadas: row.apartamento_respostas_programadas,
    },
    faq: {
      ferro_passar: row.apartamento_ferro_passar ,
      secador: row.apartamento_secador_cabelo ,
      roupa_de_cama: 'Sim, o enxoval é fornecido pela Forest.',
      toalha: 'Sim, o enxoval é fornecido pela Forest.',
      garagem: row.apartamento_tem_garagem ,
      cafeteira: row.apartamento_cafeteira,
      ventilador: row.apartamento_ventilador,
      sanduicheira: row.apartamento_sanduicheira,
      chaleira_eletrica: row.apartamento_chaleira_eletrica,
      liquidificador: row.apartamento_liquidificador,
      air_fryer: row.apartamento_air_fryer,
      smart_tv: row.apartamento_smart_tv,
      tv_aberta: row.apartamento_tv_aberta,
      tv_quarto: row.apartamento_tv_quarto,
      tipo_chuveiro: row.apartamento_tipo_chuveiro,
      tipo_fogao: row.apartamento_tipo_fogao,
      escritorio: row.apartamento_escritorio,
      aquecedor: row.apartamento_aquecedor,
      aspirador_de_po: row.apartamento_aspirador_de_po,
      ssid_wifi: row.apartamento_ssid_wifi,
      senha_wifi: row.apartamento_senha_wifi,
      aceita_pet: row.apartamento_aceita_pet,
      ar_condicionado: row.apartamento_ar_condicionado,
      andar: row.apartamento_andar,
      tensao_tomadas: row.apartamento_tensao_tomadas,
      possui_tomada_220: row.apartamento_possui_tomada_220,
      localizacao_lixeira: row.apartamento_localizacao_lixeira,
      localizacao_lavanderia: row.apartamento_localizacao_lavanderia,
      exame_piscina: row.apartamento_exame_piscina,
      pode_hospede_piscina: row.apartamento_pode_hospede_piscina,
      piscina_aquecida: row.apartamento_piscina_aquecida,
      tamanho_vaga: row.apartamento_tamanho_vaga,
    },
    predio: {
      id: row.predio_id,
      nome: row.predio_nome,
      piscina: row.piscina,
      academia: row.academia,
      churrasqueira: row.churrasqueira,
      salao_de_festas: row.salao_de_festas,
      espaco_gourmet: row.espaco_gourmet,
      sauna: row.sauna,
      spa: row.spa,
      salao_de_jogos: row.salao_de_jogos,
      coworking: row.coworking,
      jardim_terraco: row.jardim_terraco,
      lavanderia: row.lavanderia,
      bicicletario: row.bicicletario,
      estacionamento_visitas: row.estacionamento_visitas,
      elevador_social: row.elevador_social,
    },
  };
};

module.exports = { getInformacoesReserva };
